VOCAB_VERSION = "v1"

CANONICAL_SKILLS = [
    "sql",
    "python",
    "excel",
    "tableau",
    "power bi",
    "data analysis",
    "data visualization",
    "product management",
    "ai product management",
    "product strategy",
    "user research",
    "a/b testing",
    "machine learning",
    "llms",
    "prompt engineering",
    "agents",
    "evaluation",
    "hallucination handling",
    "api integration",
    "backend systems",
    "system design",
    "data flows",
    "workflow design",
    "prd writing",
    "decision trees",
    "decision engines",
    "workflow automation",
    "document processing",
    "data extraction",
    "prototyping",
    "stakeholder management",
    "go-to-market",
    "market research",
    "business analysis",
    "requirements gathering",
    "process improvement",
    "communication",
    "problem solving",
    "ownership",
    "shipping",
    "customer discovery",
    "statistics",
    "experimentation",
]

SYNONYM_MAP = {
    "ml": "machine learning",
    "machine-learning": "machine learning",
    "large language model": "llms",
    "large language models": "llms",
    "llm": "llms",
    "prompting": "prompt engineering",
    "prompts": "prompt engineering",
    "evaluation loops": "evaluation",
    "evals": "evaluation",
    "ai-native product manager": "ai product management",
    "ai native product manager": "ai product management",
    "ai product manager": "ai product management",
    "pm": "product management",
    "product mgr": "product management",
    "product thinking": "product management",
    "prd": "prd writing",
    "prds": "prd writing",
    "structured prds": "prd writing",
    "logic definitions": "prd writing",
    "ab testing": "a/b testing",
    "a/b": "a/b testing",
    "api": "api integration",
    "apis": "api integration",
    "rest api": "api integration",
    "rest apis": "api integration",
    "backend": "backend systems",
    "backend system": "backend systems",
    "system architecture": "system design",
    "architecture": "system design",
    "workflows": "workflow design",
    "ai-first workflows": "workflow design",
    "ai first workflows": "workflow design",
    "decisioning": "decision engines",
    "decision engine": "decision engines",
    "decision tree": "decision trees",
    "document extraction": "data extraction",
    "documents": "document processing",
    "mvp": "prototyping",
    "mvps": "prototyping",
    "low-code": "prototyping",
    "no-code": "prototyping",
    "customer workflows": "customer discovery",
    "customer pain points": "customer discovery",
    "bias toward action": "ownership",
    "0 to 1": "product management",
    "0 1": "product management",
    "early-stage": "product management",
    "shipped features": "shipping",
    "ship ai-powered products": "shipping",
    "shipping products": "shipping",
    "gtm": "go-to-market",
    "data viz": "data visualization",
    "dataviz": "data visualization",
    "powerbi": "power bi",
    "ms excel": "excel",
    "microsoft excel": "excel",
    "req gathering": "requirements gathering",
    "requirements": "requirements gathering",
}
