VOCAB_VERSION = "v1"

CANONICAL_SKILLS = [
    "sql",
    "python",
    "excel",
    "tableau",
    "power bi",
    "data analysis",
    "data visualization",
    "product management",
    "product strategy",
    "user research",
    "a/b testing",
    "machine learning",
    "llms",
    "prompt engineering",
    "api integration",
    "stakeholder management",
    "go-to-market",
    "market research",
    "business analysis",
    "requirements gathering",
    "process improvement",
    "communication",
    "problem solving",
    "statistics",
    "experimentation",
]

SYNONYM_MAP = {
    "ml": "machine learning",
    "machine-learning": "machine learning",
    "large language model": "llms",
    "large language models": "llms",
    "llm": "llms",
    "prompting": "prompt engineering",
    "pm": "product management",
    "product mgr": "product management",
    "ab testing": "a/b testing",
    "a/b": "a/b testing",
    "api": "api integration",
    "apis": "api integration",
    "rest api": "api integration",
    "rest apis": "api integration",
    "gtm": "go-to-market",
    "data viz": "data visualization",
    "dataviz": "data visualization",
    "powerbi": "power bi",
    "ms excel": "excel",
    "microsoft excel": "excel",
    "req gathering": "requirements gathering",
    "requirements": "requirements gathering",
}

